#!/bin/sh
set -e

# Run git_maintenance_tasks only if not running already
DEVDIR="$(readlink -e "$(dirname $0)/../../dev")"
mkdir -p ~/lmms-repo
flock -w 0 ~/lmms-repo/git_maintenance_tasks.lock \
	"$DEVDIR/git_maintenance_tasks"
