#!/bin/sh
set -e

CRONPWD="$PWD"

if [ ! -e ~/github-repo ]
then
	mkdir ~/github-repo
fi
cd ~/github-repo

if [ -e lmms ]
then
	cd lmms
	PULLRES=$(git pull)
	if [ "$PULLRES" = "Already up-to-date." -a -e maintenance-tasks-done ]
	then
		exit
	fi
else
	git clone https://github.com/LMMS/lmms
	cd lmms
fi

rm -f maintenance-tasks-done

run-parts --exit-on-error "$CRONPWD/../tasks/lmms"

if [ "$(git diff)" ]
then
	git add -u
	git commit -m "Maintenance tasks"
	git push
fi

touch maintenance-tasks-done
