#!/bin/sh
set -e -o pipefail

YEAR=$(date -u +%Y)
while true
do
	if [ "$(git log -n 1 --since=$YEAR-01-01T00:00:00Z)" ]
	then
		break
	fi
	YEAR=$((YEAR - 1))
done

sed -e "/^SET(PROJECT_YEAR / c SET(PROJECT_YEAR $YEAR)" -i CMakeLists.txt

git add CMakeLists.txt
if [ "$(git diff HEAD)" ]
then
	git commit -m "Update PROJECT_YEAR"
fi
