#!/bin/bash
echo "This device currently defined the following locales:"
locale -a

echo "Updating translation template..."
srctop=$(realpath "$(dirname "$0")"/../)

for f in "${srctop}/translations/"messages.*.xlf
do
    # Test if PHP/Symfony can load the translation
    locale="$(basename "$f")"
    locale="${locale/.xlf/}"
    locale="${locale/messages./}"
    ./bin/console translation:extract --force --prefix='' -- "$locale"
done
