ALTER TABLE users ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE files ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE filetypes ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE ratings ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE categories ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE subcategories ENGINE=InnoDB CHARSET=utf8;
ALTER TABLE licenses ENGINE=InnoDB CHARSET=utf8;
