#!/usr/bin/env bash
export APP_ENV=prod 
export APP_DEBUG=0
php bin/console cache:clear
php bin/console cache:warmup
pushd $(dirname $0)/../public

pushd forum/cache
rm -f tpl_proboot3_overall_header.html.php tpl_proboot3_overall_footer.html.php
popd

popd
